"""notes changed model

Revision ID: 60bc746cfbd6
Revises: d313d5a643df
Create Date: 2024-10-21 00:15:01.586964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bc746cfbd6'
down_revision: Union[str, None] = 'd313d5a643df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notes', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('notes', 'uri')
    op.drop_column('notes', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'url')
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
