"""remove notes url

Revision ID: e5489314eeaf
Revises: 60bc746cfbd6
Create Date: 2024-10-25 00:47:12.626064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5489314eeaf'
down_revision: Union[str, None] = '60bc746cfbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
